stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version --no-transfer-progress"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: "overlay2"
  TESTCONTAINERS_RYUK_DISABLED: "true"

services:
  - name: docker:25-dind
    entrypoint: [ "" ]
    command: [ "dockerd", "--host=tcp://0.0.0.0:2375", "--tls=false", "--storage-driver=overlay2" ]

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: never
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: never
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  image: maven:3.9.4-eclipse-temurin-17
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: never
  script:
    - mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days
  cache:
    policy: pull

docker_build:
  stage: deploy
  image: docker:25
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_COMMIT_BRANCH == "master"'
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_USERNAME/springtodo:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_USERNAME/springtodo:$CI_COMMIT_SHORT_SHA